# Generated by Django 4.2.21 on 2025-05-30 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("complaints", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="complaint",
            name="email",
        ),
        migrations.RemoveField(
            model_name="complaint",
            name="name",
        ),
    ]
